spring:
  r2dbc:
    url: r2dbc:h2:mem:///companydb
    username: sa
    password:

  sql:
    init:
      mode: always

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui
